### ISSUE TITLE
PeanutButterINI Encoding

### ISSUE THREAD

**Issue by thopper** [fluffynuts/PeanutButter#12]
We are having issues with chinese characters being displayed in Notepad, when PeanutButterINI
creates / saves a file. I use notepad++ in development but the help desk needs open the INI in notepad, which encodes the strings into chinese characters, for some reason.

I have a WPF application in which, i hold the global object
 public INIFile dvINI { get; set; }
Before the app is initialized, i'm doing some checks
         if (Directory.Exists(assyPath))
            {
                if (File.Exists(assyPath + "\\DVSettings.ini"))
                {
                    dvINI = new INIFile(assyPath + "\\DVSettings.ini");
Then Checking and setting some properties:
ex:    //If Key doesnt exist, Create it
                    if (!dvINI.HasSetting("DrawingViewer", "EnableLogging"))
                    {
                        dvINI["DrawingViewer"]["EnableLogging"] = "False";
                    }
                    enableLogging = Convert.ToBoolean(dvINI["DrawingViewer"]["EnableLogging"]);

I've tried changing the encoding in notepad++ but PBINI only reads UTF-8 correctly.

When the app runs it creates the ini with preset variables with string paths
ex: [Main-WHQ]
DEVPath="\\XXXX\XXXXX\XXX\manufacturing\"
MaxHistory="60"

Then when the app closes it resaves certain variables.
I tried to save these to a different file, in which at first glance seemed to work, but then
the chinese characters came back.

Is there any fix that i can look at to resolve this issue?
Is there any option to force the encoding to UTF-8?

**Comment by fluffynuts** [comment]
This issue was resolved as "Notepad is broken" :/

BTW, when I relayed this story to a colleague, he'd had a very similar issue in a completely different project.

For clarification: PeanutButter.INI _does_ read and write all files in UTF-8. There just seem to be some "magic" sequences of strings which flip Notepad.exe into "Chinese mode". The text is fine -- and readable as _not_ Chinese on any other sane editor. ¯\_(ツ)_/¯
