### ISSUE TITLE
How to use PeanutButterINI

### ISSUE THREAD

**Issue by Flakie99** [fluffynuts/PeanutButter#25]
C# Windows Forms. I am new to C# and cannot follow how to use this. Do you have simple instructions anywhere for a novice? I have created a test app in C# Win forms. I installed PeanutButterINI using NuGet and have copied the tests to the project. I get many errors about missing namespaces and strings not existing in current context (amongst other errors).

In my project (not the test) I have successfully used Application Settings to save and load user settings for the values of controls on my form. I have a checkbox and code where I can set whether this happens automatically (at application start and close), or not. I also have a menu so I can load them and save them during runtime. This is all using the default user.config.

Does INI read the Application Settings or is it completely separate?

I want to be able to save and load Application settings to different files so I can have multiple Application Setting sets.
Can PeanutButterINI be configured to do this?

**Comment by Flakie99** [comment]
For the example code you give on your b;log I get: System.Collections.Generic.KeyNotFoundException: 'FavouriteColor'

**Comment by fluffynuts** [comment]
Hi

Thanks for submitting an issue (:

First off, here's a demo I cracked together for using PeanutButter.INI from a WinForms app: https://github.com/fluffynuts/PeanutButter.INI.WinForms.Demo

Hopefully it answers your questions about _how_ to use PeanutButter.INI

To answer your other questions here:

1. What are ApplicationSettings
I'm assuming that you're reading from `appSettings` in your app.config (which is output alongside your .exe as whatever-your-program-is-called.exe.config), and that you're probably using ConfigurationManager, [like the MSDN docs](https://docs.microsoft.com/en-us/dotnet/api/system.configuration.configurationmanager.appsettings?view=netframework-4.8)

In this case, you're reading from (and eventually writing to) an xml file, and only dealing with a very specific part of that xml file

There are pros and cons with different forms of configuration (as there are with all things), but in this case, if we are to compare app.config (xml) vs INI files:

1. You only have one app.config for your application. You can't (easily) swap them out at runtime -- the infrastructure is just not designed for it.
2. app settings are in xml -- which is often more difficult for people to deal with than [INI format](https://en.wikipedia.org/wiki/INI_file), but not impossible, of course
3. there's no concept of "sections" within app settings, where INI files have this concept baked in -- you can get around this in app settings, of course, (eg name your settings like "Section1.Setting1")

2. Does PeanutButter.INI read from / write to application settings?
No. As you've probably figured out from above, the files are in totally different formats.

3. So why use PeanutButter.INI?
	1. If you prefer the INI format for settings (as I say, quite a few people find INI easier to read and write by hand than xml)
	2. If you'd like to easily load up different configuration files at runtime

4. What does this exception mean: `System.Collections.Generic.KeyNotFoundException: 'FavouriteColor'`
Ok, so PeanutButter.INI abstracts how INI files work by presenting the developer with a dictionary of dictionaries.

So, since you've said you're new to this, a quick rundown of dictionaries:
A dictionary in .NET is a collection of key/value pairs which are quick to read from, even if there are a lot of keys. Keys would be equivalent to "setting names" and values equivalent to "setting values" for your use-case

.NET Dictionaries are found in the `System.Collections.Generic` namespace, because they are _generic_ collections: you can create a dictionary and tell it what type the keys and values will be -- they can be anything, but they will be consistent for all key/value pairs in the collection.

PeanutButter uses `Dictionary<string, string>`, so keys are strings, and so are the values. Looking closer, `IINIFile` presents a top-level dictionary of sections, so if you load the file:
```ini
[general]
foo=bar
```
you can reference `ini["general"]` and you'll get a dictionary containing one key/value pair: "foo" => "bar". You can "reach directly into" the second dictionary, if you know for sure that the setting exists:

```csharp
var fooValue = ini["general"]["foo"];
```

However, if you asked for:
```csharp
var anotherValue = ini["general"]["another"];
```
you'd get a `KeyNotFoundException`, because the `general` section doesn't have a setting called `another`. You can ask IINIFile if a setting exists though:

```csharp
if (ini.SettingExists("general", "another"))
{
	Console.WriteLine($"general.another is: {ini["general"]["another"]}");
}
else
{
	Console.WriteLine("no 'another' setting found in section 'general');
}
```

PeanutButter.INI also makes section generation transparent, so you can just directly assign to a value in a section which doesn't (yet) exist, and that's ok:
```csharp
ini["new-section"]["setting"] = "hello";
```

Anyways, check out the demo -- I hope it helps (:

**Comment by Flakie99** [comment]
Wow, thanks very much for this. It will be some interesting reading. Hopefully I can get it all working.
I have just setup a new Settings Provider and am testing it now. All seems to be working well and the xml is now saving in the application folder. So all good as I need this app to be portable when finished
But I still want to implement this with ini files as i need the multiple configs as well as portable..

**Comment by Flakie99** [comment]
Thanks very much for the demo. I have had a quick look at it now and it is amazing. Much better than I was hoping for, I am sure I will be able to use this in my application. I will not know the amount of ini files I will be using. Potentially, in the future, it could be hundreds and the name will change a lot for each one (it will be based on a persons name and the device type they are using). I am sure I can code something now. Fantastic  Thanks again.
