### ISSUE TITLE
semi-colon ini text value causes truncation (2022)

### ISSUE THREAD

**Issue by AxelTechnology** [fluffynuts/PeanutButter#55]
I'm trying to use PeanutButter.INI but it truncates text at every ; because it considers that sign a comment.
I suppose I should create a new ILineParser to tell the library to do not stop reading at ; but I cannot figure out how. 
Do you have any documentation?

Use case:
[PATHS]
'The line below contains the SQL connection string to customer DB
DBPATH=DRIVER={SQL Server};SERVER=192.168.85.130\SQLEXPRESS02;DATABASE=OneSQL;UID=sa;PWD=pazzword;TRUSTED_CONNECTION=NO;CONNECTION TIMEOUT=60;

In my case, comments are full lines only, started with ' char, while ; it's a valid char.

Suggested solutions:
1) allow to choose comment char. For example, ' instead of ; (current default)
2) allow to choose comment detection as:
     -contains (current default)
     -startsWith
     -never
3) document how to create a class to implement ILineParser with as small as possibile code needed

Thank you,
Matteo Farina

**Comment by fluffynuts** [comment]
There's been a lot of discussion over commenting in INI files, some of it here: https://stackoverflow.com/questions/1378219/do-standard-windows-ini-files-allow-comments. The best spec for INI file comments is here: https://en.wikipedia.org/wiki/INI_file#Comments (and this doesn't even suggest lines with trailing comments, though I've seen the windows ini parser deal with this before).

These all suggest that the correct commenting character for INI is the semi-colon (`;`). However, semi-colons may be put into quoted strings: https://en.wikipedia.org/wiki/INI_file#Quoted_values

Is there any reason why your INI file can't look like the following?

```
[PATHS]
; The line below contains the SQL connection string to customer DB
DBPATH="Driver={SQL Server};Server=192.168.85.130\SQLEXPRESS02;DATABASE=OneSQL;UID=sa;PWD=pazzword;TRUSTED_CONECTION=NO;CONNECTION TIMEOUT=60;"
```

I've proven that this is already supported with https://github.com/fluffynuts/PeanutButter/blob/29c8388a8afcaa2e8b45ed1886b0140f23fae6a7/source/INI/PeanutButter.INI.Tests/TestINIFile.cs#L431

This is not to tell you that the solution to your problem is simply to do it "my way" - part of the reason for ubiquitous formats like INI is that so many things understand how to read them. If you try to read the INI file as described in this issue with another tool, it will exhibit the same result - making your INI file no longer portable 😔

If there is no way around this behavior for you, I'm willing to expose a protected field on BestEffortLineParser, `CommentDelimiter` which you can use to set the comment delimiter in a derived class (much as you are doing now, and it will also cope with lines commented by whatever you please). 
However, I would _heartily discourage_ such usage as, at the expense of repeating myself, it means that your INI files wouldn't be portable - they would only be readable by your code.

**Comment by AxelTechnology** [comment]
> "Is there any reason why your INI file can't look like the following?"

It's about legacy code and legacy files, which I have to live with. 
About portability, that's not really a requirement.

**Comment by fluffynuts** [comment]
I'll push a package

**Comment by AxelTechnology** [comment]
Is it possible that I cannot inherit from BestEffortLineParser because it is internal?
![immagine](https://user-images.githubusercontent.com/18584211/155162359-09e1f7af-6364-42d9-b59a-1535abcabe42.png)

**Comment by fluffynuts** [comment]
It should be public in 2.0.62. It used to be internal to reduce the noise of exported types. Have you updated?

**Comment by fluffynuts** [comment]
I can confirm that, in a brand new project targeting 2.0.62, I can derive from `BestEffortLineParser`:

![image](https://user-images.githubusercontent.com/4669340/155273889-e5d1aa6a-1cfe-4365-abc8-22355378ff3b.png)

**Comment by AxelTechnology** [comment]
Yes, it works, thank you!

Do you think that is a good idea that in case of 
base.CommentDelimiter = "";
the comments are never stripped out of the line, so the whole line is returned?

Use cases:
[DESCRIPTION]
MESG-32=Industrie de l'emballage et fabrication d'autres matériaux
PWD-ENCRIPTED=xLvA'M3%^GKSV

**Comment by fluffynuts** [comment]
hm, wow, you have some really gnarly ini files to deal with! if you're trying to prevent any comment parsing whatsoever, I'd probably put some non-printable character in there, like char 0 or something like that? You'd want to not match on _anything_, so any character which isn't in your input file will do the trick - if you have a real null in your ini file, that would be Bad :D so yeah, perhaps

```csharp
CommentDelimiter = "\0";
```

**Comment by fluffynuts** [comment]
again, I'd suggest processing these ini files to standard formats - perhaps your systems could (once-off) load up with the derivative line parser, with CommentDelimiter set to "\0" and rewrite the files, then open again? You'd want to record somewhere that you did this work so it's not done every time. I'm just thinking about the next poor person who has to deal with these files and doesn't have a PeanutButter to help :joy:
