### ISSUE TITLE
PeanutButter.INI request for new Load overload

### ISSUE THREAD

**Issue by AxelTechnology** [fluffynuts/PeanutButter#99]
## Expected Behavior
Load() a non-existing file should not create folders nor file. 
It should just work in memory until the .Persist() calling.

## Actual Behavior
Load() creates full path directories path and a 0 byte file, in case of missing.
The creation is performed into GetLinesFrom() and there's no way to avoid it.

## Steps to Reproduce the Problem
  1. call Load() to a non-existing file
  2.
  3.

## Specifications

  - Platform: Windows 10 x64
  - PeanutButter Component: PeanutButter .INI
  - PeanutButter Version: 3.0.180

## Suggestions:
1) create an Load overload method with bool ensureFileExist   (= false)
2) create a new method (example:  Create(string fileName) that doesn't write anything until .Persist()
3) allow to set this.Path from outside (now it's read-only)

Thank you.

**Comment by fluffynuts** [comment]
Hi

In this use-case, if I understand what you want properly, you could skip the initial `Load` (it has no purpose - it's not loading anything as the file doesn't exist) and later call `Persist` with the path where you'd like to save to.

eg:
```csharp
var ini = new INIFile();
ini.SetValue("section", "setting", "value");
ini.Persist("/path/to/config.ini");
```

Could this work for you?

The reasoning behind the current behaviors is:
1. if attempting to Load(), and the file doesn't exist, it's assumed that the caller does expect the file to exist - creating it not only prevents issues when attempting to actually load a little later, but "reserves" the file name - another process, looking for that file, would find it. If you Load(), you may like to Persist() later, and 
2. the Path will be set - immutable - so that (a) Persist later doesn't need the path (if unchanged) and because swapping out that path half-way along is undefined: if the path is changed, an observer would expect the config in IINIFile to have come from that path.

**Comment by AxelTechnology** [comment]
Yes!
Thank you
